#!/command/with-contenv bash
# shellcheck shell=bash

# svc-kopia-server main
main() {
    # This will prepend service name to all output from here
    exec > >(while read -r line; do echo "[svc-kopia-server] ${line}"; done) 2>&1

    exec /usr/local/bin/kopia-server-wrapper
}

 main