#!/usr/bin/env bash

random_string() {
    local length="${1:?}"
    tr -dc 'a-zA-Z0-9!@#$%^&*()-=_+[]{};:,.<>?`~' </dev/urandom | head -c "${length}"
}

main() {
    local secretsDir="${DOCKER_SECRETS_DIR:-./secrets}"
    local secretFile="${1:?}"
    local length="${2:-32}"
    local secretFilePath="${secretsDir}/${secretFile}"

    mkdir -p "${secretsDir}"

    if [ -f "${secretFilePath}" ]; then
        printf "Warning: Secret file already exists and will be overwritten: %s\n" "${secretFilePath}" >&2
        sleep 5
    fi

    if ! (random_string "${length}" >"${secretFilePath}"); then
        printf "Error: Failed to write secret file: %s\n" "${secretFilePath}" >&2
        return 1
    fi

    chmod 600 "${secretFilePath}"

    printf "Wrote %d bytes to %s\n" "${length}" "${secretFilePath}"
}

main "${@}"
